---
users:

  'plone':
    name: 'Plone installation'
    email: 'contato@smkbarbosa.eti.br'
    public_keys:
      - 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIC0OMheAljJUCD29OXDMR4i7YEfBA37pAumm5bDLdR9X contato@smkbarbosa.eti.br'
    password: '$6$8TrTq/2twy7u./bS$5gxT7m93.aVJD1P9V0y.EMcCvgH2RV8pM4vVyGFpqx3zEPUvmib7nQtJD6vxJRTMyR9oPRi323tbwpx0wLyWs.'
    state: present
    shell: '/bin/bash'
    groups:
      - 'docker'
      - 'plone'
